language: node_js
node_js:
  - "8"
install:
  - npm install -g codecov jest
  - npm install babel-preset-env jest-canvas-mock @tensorflow-models/posenet @tensorflow/tfjs lodash custom-event-polyfill
script:
  - jest --coverage --detectOpenHandles && codecov
